#!/bin/bash

# Slackware updater script for XiMpLe

# Copyright 2025-2026 Antonio Leal, Porto Salvo, Oeiras, Portugal
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=XiMpLe
set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR

################################
# check versions               #
################################
AUX=$(links -dump https://www.ximple.cz/download.php | grep version | awk '{print $NF}')
TAG=${AUX//\"/}
REALVERSION=${TAG}
NEWVERSION=${REALVERSION/-/_}

TARBALL1="XiMpLe(32bit).exe"
TARBALL2="XiMpLe.exe"
TARBALL3="XiMpLe.pdf"
URL1="https://www.ximple.cz/files.net4/$TARBALL1"
URL2="https://www.ximple.cz/files.net4/$TARBALL2"
URL3=" http://www.ximple.cz/files/$TARBALL3"

VERSION=`cat version`
if [ "$VERSION" = "$NEWVERSION" ]
then
    echo -n "is at version $VERSION"
    export RET0=""
else
    ################################
    # check for testonly parameter #
    ################################
    if [ "$ARG0" = "TESTONLY" ]
    then
        echo -n "has a new version $NEWVERSION"
        export RET0=$NEWVERSION
        return
    fi
    ################################
    # download tarball             #
    ################################
    wget $URL1
    wget $URL2
    wget $URL3

    if [ ! -f ./$TARBALL1 ]
    then
        echo "File $TARBALL1 not found, aborting..."
        exit
    fi
    if [ ! -f ./$TARBALL2 ]
    then
        echo "File $TARBALL2 not found, aborting..."
        exit
    fi
    if [ ! -f ./$TARBALL3 ]
    then
        echo "File $TARBALL3 not found, aborting..."
        exit
    fi
    # delete old tarball and place new one
    rm -rf ../$TARBALL1 2> /dev/null
    rm -rf ../$TARBALL2 2> /dev/null
    rm -rf ../$TARBALL3 2> /dev/null
    mv $TARBALL1 ..
    mv $TARBALL2 ..
    mv $TARBALL3 ..

    ################################
    # write templates              #
    ################################
    MD51=`md5sum ../$TARBALL1 | cut -d " " -f 1`
    MD52=`md5sum ../$TARBALL2 | cut -d " " -f 1`
    MD53=`md5sum ../$TARBALL3 | cut -d " " -f 1`
    #DATEVERSION=`tar tvfz ../$TARBALL | head -n1 | awk '{ print $4 }' | awk 'BEGIN { FS = "-" } ; { print $1$2$3 }'`

    sed -e "s/_version_/${NEWVERSION}/g" \
        -e "s/_md51_/${MD51}/g" \
        -e "s/_md52_/${MD52}/g" \
        -e "s/_md53_/${MD53}/g" \
        $SCRIPT_DIR/template/${PRGNAM}.info.template > ../${PRGNAM}.info

    sed -e "s/_version_/${NEWVERSION}/g" \
        $SCRIPT_DIR/template/${PRGNAM}.SlackBuild.template > ../${PRGNAM}.SlackBuild

    chmod 644 ../${PRGNAM}.SlackBuild
    echo "$NEWVERSION" > version
    echo -n "has a new version $NEWVERSION"
    export RET0=$NEWVERSION
fi
