#!/bin/bash

# Slackware updater script for reaper

# Copyright 2025-2026 Antonio Leal, Porto Salvo, Oeiras, Portugal
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=reaper
set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR

################################
# check versions               #
################################
#NEWVERSION=$(curl -s https://api.github.com/repos/<repo>/reaper/releases/latest |  jq -r '.tag_name')
NEWVERSION=$(lynx --dump https://www.reaper.fm/ | grep "VERSION" | awk '{print substr($2,0,length($2)-1)}')
MINIVERSION=${NEWVERSION/./}
TARBALL32=reaper${MINIVERSION}_linux_i686.tar.xz
URL32="https://www.reaper.fm/files/${NEWVERSION:0:1}.x/$TARBALL32"
TARBALL64=reaper${MINIVERSION}_linux_x86_64.tar.xz
URL64="https://www.reaper.fm/files/${NEWVERSION:0:1}.x/$TARBALL64"

VERSION=`cat version`
if [ "$VERSION" = "$NEWVERSION" ]
then
    echo "is at version $VERSION"
    export RET0=""
else
    ################################
    # check for testonly parameter #
    ################################
    if [ "$ARG0" = "TESTONLY" ]
    then
        echo "has a new version $NEWVERSION"
        export RET0=$NEWVERSION
        return
    fi
    ################################
    # download tarball             #
    ################################
    wget $URL32
    if [ ! -f ./$TARBALL32 ]
    then
        echo "File $TARBALL32 not found, aborting..."
        exit
    fi
    wget $URL64
    if [ ! -f ./$TARBALL64 ]
    then
        echo "File $TARBALL64 not found, aborting..."
        exit
    fi

    # delete old tarball and place new one
    rm -rf ../*.tar.xz 2> /dev/null
    mv *.tar.xz ..

    ################################
    # write templates              #
    ################################
    MD532=`md5sum ../$TARBALL32 | cut -d " " -f 1`
    MD564=`md5sum ../$TARBALL64 | cut -d " " -f 1`
    #DATEVERSION=`tar tvfz ../$TARBALL | head -n1 | awk '{ print $4 }' | awk 'BEGIN { FS = "-" } ; { print $1$2$3 }'`

    sed -e "s/_version_/${NEWVERSION}/g" \
        -e "s/_miniversion_/${MINIVERSION}/g" \
        -e "s/_md532_/${MD532}/g" \
        -e "s/_md564_/${MD564}/g" \
        $SCRIPT_DIR/template/${PRGNAM}.info.template > ../${PRGNAM}.info

    sed -e "s/_version_/${NEWVERSION}/g" \
        $SCRIPT_DIR/template/${PRGNAM}.SlackBuild.template > ../${PRGNAM}.SlackBuild

    chmod 644 ../${PRGNAM}.SlackBuild
    echo "$NEWVERSION" > version
    echo "has a new version $NEWVERSION"
    export RET0=$NEWVERSION
fi
