#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#**********************************************************************************
#*                                                                                *
#*                                   Silk Fontend                                 *
#*          ------------------------------------------------------------          *
#*                                                                                *
#**********************************************************************************
#
# Copyright 2025 Antonio Leal, Porto Salvo, Portugal
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# $Id:$

import sys
import os
import subprocess
import configparser
import ast

VERSION = '20251109_9f8624c'

# https://stackabuse.com/how-to-print-colored-text-in-python/
ESC = '\033['
NORMAL, BOLD, LIGHT, ITALIC, UNDERLINE, BLINK = [0, 1, 2, 3, 4, 5]
BLACK, RED, GREEN, YELLOW, BLUE, PURPLE, CYAN, WHITE = [30, 31, 32, 33, 34, 35, 36, 37]
def checkcolor(style, foreground, background):
    if style not in [NORMAL, BOLD, LIGHT, ITALIC, UNDERLINE, BLINK]: return False
    if foreground not in [BLACK, RED, GREEN, YELLOW, BLUE, PURPLE, CYAN, WHITE]: return False
    if background not in [BLACK, RED, GREEN, YELLOW, BLUE, PURPLE, CYAN, WHITE]: return False
    return True
def defcolor(style, foreground, background):
    if checkcolor(style, foreground, background):
        return f'{ESC}{style};{foreground};{background+10}m'
    return ''
def setcolor(style, foreground, background):
    print(defcolor(style,foreground,background), end='')
def undefcolor():
    return f'{ESC}0;0m'
def resetcolor():
    print(undefcolor(), end='')
def style2int(style):
    values = { 'NORMAL': 0, 'BOLD': 1, 'LIGHT': 2, 'ITALIC': 3, 'UNDERLINE': 4, 'BLINK': 5 }
    return values[style]
def color2int(color):
    values = { 'BLACK': 30, 'RED': 31, 'GREEN': 32, 'YELLOW': 33, 'BLUE': 34, 'PURPLE': 35, 'CYAN': 36, 'WHITE': 37 }
    return values[color]


def usage():
    print (f"{defcolor(BOLD, WHITE, BLACK)}Silk is a practical frontend to various slackware package management tools,")
    print (f"namely slapt-get, slapt-src, sbopkg and slackpkg.{undefcolor()}")
    print ()
    print ("Usage: silk command [options] [programs]")
    print ("       slapt command [options] [programs]")
    print ("       sl command [options] [programs]")
    print ()
    print ("commands:")
    print ("    u, update                    retrieve metadata related to packages and slackbuilds, does not change your system")
    print ("    U, upgrade                   upgrade installed packages and upgrade all installed slackbuilds")
    print ("    s, search                    search stuff")
    print ("    b, build   [programs]        download package / build slackbuilds ")
    print ("    i, install [programs]        install package / install slackbuilds ")
    print ("    c, clean                     clean caches")
    print ("    r, remove  [programs]        remove packages")
    print ("    l, list                      list packages")
    print ("")
    print ("where [programs] is a list of space separated package names")
    print ("")
    print ("options:")
    print ("    -y                           do not prompt for install/upgrade, assume yes")
    print ("")
    print (f"{defcolor(BOLD, WHITE, BLACK)}The program defines the symlinks 'slapt' and 'sl' pointing to the 'silk'.")
    print (f"Please also check ~/.config/silkrc settings to decide which tools you want to run.{undefcolor()}")
    print ()

def execute(lines):
    #print(lines)
    with open('/tmp/silk', 'w') as file:
        file.writelines(lines)
    os.system('chmod +x /tmp/silk')
    subprocess.call('/tmp/silk')

def slapt_get(command, options, programs=""):
    localops = ''
    localcmd = ''
    if command in ['u', 'update']:
        localcmd = '-u'
    if command in ['U', 'upgrade']:
        localcmd = '--upgrade'
    if command in ['s', 'search']:
        localcmd = '--search'
    if command in ['b', 'build']:
        localcmd = '-d --install'
    if command in ['i', 'install']:
        localcmd = '--install'
    if command in ['c', 'clean']:
        localcmd = '--clean'
    if command in ['r', 'remove']:
        localcmd = '--remove'
    if command in ['l', 'list']:
        localcmd = '--available'
    for op in options.split():
        if op == '-y':
            localops = localops + "-y "
    localops = localops.strip()
    if localcmd != "":
        print(f'++++ Running sudo /usr/sbin/slapt-get {localops} {localcmd} {programs}\n')
        lines = ['#!/bin/bash\n\n', f'sudo /usr/sbin/slapt-get {localops} {localcmd} {programs}\n']
        execute(lines)
    else:
        usage()
        exit(0)

def slapt_src(command, options, programs=""):
    localops = ''
    localcmd = ''
    if command in ['u', 'update']:
        localcmd = '-u'
    if command in ['U', 'upgrade']:
        localcmd = '--upgrade-all'
    if command in ['s', 'search']:
        localcmd = '--search'
    if command in ['b', 'build']:
        localcmd = '--build'
    if command in ['i', 'install']:
        localcmd = '--install'
    if command in ['c', 'clean']:
        localcmd = '--clean'
    if command in ['r', 'remove']:
        return
    if command in ['l', 'list']:
        localcmd = '--list'
    for op in options.split():
        if op == '-y':
            localops = localops + "-y "
    localops = localops.strip()
    if localcmd != "":
        print(f'++++ Running sudo /usr/bin/slapt-src {localops} {localcmd} {programs}\n')
        lines = ['#!/bin/bash\n\n', f'sudo /usr/bin/slapt-src {localops} {localcmd} {programs}\n']
        execute(lines)
    else:
        usage()
        exit(0)

def sbopkg(command, programs=""):
    if command in ['u', 'update']:
        print(f'++++ Running sudo /usr/sbin/sbopkg -r\n')
        lines = ['#!/bin/bash\n\n', f'sudo /usr/sbin/sbopkg -r\n']
        execute(lines)
    elif command in ['U', 'upgrade']:
        print(f'++++ Running sudo /usr/sbin/sbopkg -c\n')
        lines = ['#!/bin/bash\n\n',
                 f'sudo /usr/sbin/sbopkg -c | sudo tee /tmp/silkout \n',
                 'cat /tmp/silkout | egrep ":$" | cut -d":" -f1 | tr \"\\n\" \" \" > /tmp/silktmp\n',
                 f'sudo /usr/sbin/sbopkg -i "`cat /tmp/silktmp`"\n']
        execute(lines)
    elif command in ['s', 'search']:
        print(f'++++ Running sudo /usr/sbin/sbopkg -g "{programs}"\n')
        lines = ['#!/bin/bash\n\n', f'sudo /usr/sbin/sbopkg -g "{programs}"\n']
        execute(lines)
    elif command in ['b', 'build']:
        print(f'++++ Running sudo /usr/sbin/sbopkg -b "{programs}"\n')
        lines = ['#!/bin/bash\n\n', f'sudo /usr/sbin/sbopkg -b "{programs}"\n']
        execute(lines)
    elif command in ['i', 'install']:
        print(f'++++ Running sudo /usr/sbin/sbopkg -i "{programs}"\n')
        lines = ['#!/bin/bash\n\n', f'sudo /usr/sbin/sbopkg -i "{programs}"\n']
        execute(lines)
    elif command in ['c', 'clean']:
        print(f'++++ Running sudo /usr/sbin/sbopkg -o\n')
        print(f'++++ Running sudo /usr/sbin/sbopkg -P\n')
        lines = ['#!/bin/bash\n\n',
                 f'sudo /usr/sbin/sbopkg -o\n',
                 f'sudo /usr/sbin/sbopkg -P\n']
        execute(lines)
    elif command in ['r', 'remove']:
        lines = ['#!/bin/bash\n\n']
        for pkg in programs.split():
            print(f'++++ Running sudo sbin/removepkg {pkg}\n')
            lines.append(f'sudo /sbin/removepkg {pkg}\n')
        execute(lines)
    elif command in ['l', 'list']:
        print(f'++++ Running sudo /usr/sbin/sbopkg -p | cat\n')
        lines = ['#!/bin/bash\n\n',
                 f'sudo /usr/sbin/sbopkg -p | cat\n']
        execute(lines)
    else:
        usage()
        exit(0)

def slackpkg(command, programs=""):
    if command in ['u', 'update']:
        print(f'++++ Running sudo /usr/sbin/slackpkg update\n')
        lines = ['#!/bin/bash\n\n', f'sudo /usr/sbin/slackpkg update\n']
        execute(lines)
    elif command in ['U', 'upgrade']:
        print(f'++++ Running sudo /usr/sbin/slackpkg install-new\n')
        print(f'++++ Running sudo /usr/sbin/slackpkg upgrade-all\n')
        lines = ['#!/bin/bash\n\n',
                 f'sudo /usr/sbin/slackpkg install-new\n',
                 f'sudo /usr/sbin/slackpkg upgrade-all\n']
        execute(lines)
    elif command in ['s', 'search']:
        lines = ['#!/bin/bash\n\n']
        for pkg in programs.split():
            print(f'++++ Running sudo /usr/sbin/slackpkg search {pkg}\n')
            lines.append(f'sudo /usr/sbin/slackpkg search {pkg}\n')
        execute(lines)
    elif command in ['b', 'build']:
        lines = ['#!/bin/bash\n\n']
        for pkg in programs.split():
            print(f'++++ Running sudo /usr/sbin/slackpkg download {pkg}\n')
            lines.append(f'sudo /usr/sbin/slackpkg download {pkg}\n')
        execute(lines)
    elif command in ['i', 'install']:
        lines = ['#!/bin/bash\n\n']
        for pkg in programs.split():
            print(f'++++ Running sudo /usr/sbin/slackpkg install {pkg}\n')
            lines.append(f'sudo /usr/sbin/slackpkg install {pkg}\n')
        execute(lines)
    elif command in ['c', 'clean']:
        print(f'++++ Running sudo /usr/sbin/slackpkg clean-system\n')
        lines = ['#!/bin/bash\n\n',
                 f'sudo /usr/sbin/slackpkg clean-system\n']
        execute(lines)
    elif command in ['r', 'remove']:
        lines = ['#!/bin/bash\n\n']
        for pkg in programs.split():
            print(f'++++ Running sudo sbin/removepkg {pkg}\n')
            lines.append(f'sudo /sbin/removepkg {pkg}\n')
        execute(lines)
    elif command in ['l', 'list']:
        print(f'++++ Running sudo rm /etc/slackpkg/templates/silk.template\n')
        print(f'++++ Running sudo /usr/sbin/slackpkg generate-template silk\n')
        print(f'++++ Running cat /etc/slackpkg/templates/silk.template\n')
        lines = ['#!/bin/bash\n\n',
                 'sudo rm /etc/slackpkg/templates/silk.template\n',
                 'sudo /usr/sbin/slackpkg generate-template silk\n',
                 'cat /etc/slackpkg/templates/silk.template\n',]
        execute(lines)
    else:
        usage()
        exit(0)

def loadconfig():
    setcolor(BOLD, RED, BLACK)
    home = os.path.expanduser('~')
    rc = f'{home}/.config/silkrc'
    config = configparser.ConfigParser()
    createfile=False
    if os.path.isfile(rc):
        config.read(rc)
        if (config.get('settings','version') != VERSION):
            createfile = True
        else:
            print(f'Loaded {home}/.config/silkrc\n')
    else:
        createfile = True
    if createfile:
        print(f'New {home}/.config/silkrc config file is invalid/older, creating a new one...\n')
        with open(f'{home}/.config/silkrc', 'w') as file:
            file.writelines('[settings]\n')
            file.writelines('version = ' + str(VERSION) + '\n\n')
            file.writelines('slapt-get-colors = NORMAL CYAN BLACK\n')
            file.writelines('slapt-src-colors = NORMAL YELLOW BLACK\n')
            file.writelines('sbopkg-colors = NORMAL GREEN BLACK\n')
            file.writelines('slackpkg-colors = NORMAL WHITE BLACK\n\n')
            file.writelines('slapt-get = true\n')
            file.writelines('slapt-src = true\n')
            file.writelines('sbopkg = true\n')
            file.writelines('slackpkg = true\n')
    resetcolor()

def main():
    if os.path.isfile('/usr/bin/xseticon'):
        os.system('xseticon -id "$WINDOWID" /usr/share/pixmaps/silk.png')
    os.system('clear')
    loadconfig()
    home = os.path.expanduser('~')
    rc = f'{home}/.config/silkrc'
    config = configparser.ConfigParser()
    config.read(rc)

    if (len(sys.argv[1:]) == 0):
        usage()
    else:
        command = sys.argv[1]
        options = ""
        programs = ""
        for arg in sys.argv[2:]:
            if arg[0] == '-':
                options=options + " " + arg
            else:
                programs = programs + " " + arg

        if bool(config.getboolean('settings','slapt-get')):
            c = config.get('settings', 'slapt-get-colors').split()
            setcolor(style2int(c[0]), color2int(c[1]), color2int(c[2]))
            slapt_get(command, options, programs)
            resetcolor()
            print()
        if bool(config.getboolean('settings','slapt-src')):
            c = config.get('settings', 'slapt-src-colors').split()
            setcolor(style2int(c[0]), color2int(c[1]), color2int(c[2]))
            slapt_src(command, options, programs)
            resetcolor()
            print()
        if bool(config.getboolean('settings','sbopkg')):
            c = config.get('settings', 'sbopkg-colors').split()
            setcolor(style2int(c[0]), color2int(c[1]), color2int(c[2]))
            sbopkg(command, programs)
            resetcolor()
            print()
        if bool(config.getboolean('settings','slackpkg')):
            c = config.get('settings', 'slackpkg-colors').split()
            setcolor(style2int(c[0]), color2int(c[1]), color2int(c[2]))
            slackpkg(command, programs)
            resetcolor()
            print()

if __name__ == '__main__':
    main()


