#!/bin/bash

# Slackware updater script for SmallBASIC

# Copyright 2025-2025 Antonio Leal, Porto Salvo, Oeiras, Portugal
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=SmallBASIC
set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR

################################
# check versions               #
################################
# TAG=$(curl -s https://api.github.com/repos/smallbasic/SmallBASIC/releases/latest | jq -r '.tag_name')
TAG=$(gh release view -R smallbasic/SmallBASIC --json tagName --jq '.tagName')
NEWVERSION=${TAG//_/\.}
TARBALL1=smallbasic-${NEWVERSION}.tar.gz
URL1="https://github.com/smallbasic/SmallBASIC/releases/download/${TAG}/${TARBALL1}"


VERSION=`cat version`
if [ "$VERSION" = "$NEWVERSION" ]
then
    echo -n "is at version $VERSION"
    export RET0=""
else
    ################################
    # check for testonly parameter #
    ################################
    if [ "$ARG0" = "TESTONLY" ]
    then
        echo -n "has a new version $NEWVERSION, but you have to update it manually"
        export RET0=$NEWVERSION
        return
    fi
fi
