#!/bin/bash

# Slackware menu for 0scripts

# Copyright 2024-2026 Antonio Leal, Porto Salvo, Oeiras, Portugal
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

CWD="$(echo `pwd`)"
PKGNAME=${PWD##*/}
HEIGHT=26
WIDTH=120
CHOICE_HEIGHT=24
BACKTITLE="Antonio Leal's \"0\" scripts SlackBuild environment at $CWD"
TITLE="$PKGNAME"
MENU="Choose one of the following:"

if ! [ -f $PKGNAME.info ]; then
  echo "You must run this script from within a SlackBuild folder."
  exit 0
fi

DIALOG_CANCEL=1
DIALOG_ESC=255

OPTIONS=()
if [ -f 0/updater ]; then
OPTIONS+=(0 "Run the updater                     - upgrade the SlackBuild package files"
         "" "-----------------------------------------------------------------------------------------------------------"
         )
fi
OPTIONS+=(1 "Run \"less $PKGNAME.info\"              - list the contents of $PKGNAME.info"
         2 "0meld                               - check if SlackBuilds.org changed the script"
         3 "0replace-string                     - uses sed in the $PKGNAME folder to replace strings"
         4 "0download-source-tarballs           - get the source code, as per $PKGNAME.info"
         5 "0update-md5-info                    - recalculates md5 and updates info file"
         "" "-----------------------------------------------------------------------------------------------------------"
         6 "0build                              - builds the package"
         7 "Open tar.gz ready SlackBuild        - open $PKGNAME.tar.gz with ark"
         "" "-----------------------------------------------------------------------------------------------------------"
         8 "0commit-push                        - local commits changes and pushes to GitHub"
         9 "0pull-request                       - generates a PR on SlackBuilds GitHub site"
         "" "-----------------------------------------------------------------------------------------------------------"
         c "0clean-tree                         - runs git clean -f on myslackbuilds"
         e "Edit files                          - edit files in the $PKGNAME folder"
         d "Run \"git diff\"                      - Compare local changes"
         s "Run \"git status\"                    - Check which files are new or have changed"
         q "Quit to DOS :)"
         )

while (true)
do
    CHOICE=$(dialog --clear \
                    --backtitle "$BACKTITLE" \
                    --title "$TITLE" \
                    --menu "$MENU" \
                    $HEIGHT $WIDTH $CHOICE_HEIGHT \
                    "${OPTIONS[@]}" \
                    2>&1 >/dev/tty)

    exit_status=$?
    exec 3>&-
    clear
    case $exit_status in
        $DIALOG_CANCEL)
        echo "Program terminated."
        exit
        ;;
        $DIALOG_ESC)
        echo "Program terminated." >&2
        exit 1
        ;;
    esac

    case $CHOICE in
            0)
                if [ -f 0/updater ]; then
                    cd 0
                    export ARG0=""
                    source updater
                    cd $CWD
                    read -p "Press [ENTER] to continue." op
                fi
                ;;
            1)
                less $PKGNAME.info
                ;;
            2)
                0meld
                ;;
            3)
                0replace-string
                read -p "Press [ENTER] to continue." op
                ;;
            4)
                0download-source-tarballs
                read -p "Press [ENTER] to continue." op
                ;;
            5)
                0update-md5-info
                read -p "Press [ENTER] to continue." op
                ;;
            6)
                0build
                read -p "Press [ENTER] to continue." op
                ;;
            7)
                echo "close ark to return to main menu..."
                ark 0/slackbuild/$PKGNAME.tar.gz 2> /dev/null
                ;;
            8)
                0commit-push
                read -p "Press [ENTER] to continue." op
                ;;
            9)
                0pull-request
                read -p "Press [ENTER] to continue." op
                ;;
            c)
                0clean-tree
                read -p "Press [ENTER] to continue." op
                ;;
            e)
                flist=()
                for f in $(ls -I0 -1)
                do
                    echo $f
                    flist+=( "$f" "" )
                done
                CHOICE=$(dialog --clear \
                                --backtitle "$BACKTITLE" \
                                --title "$TITLE" \
                                --menu "Choose file to edit:" \
                                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                                "${flist[@]}" \
                                2>&1 >/dev/tty)
                exit_flist=$?
                if ! [[ "$exit_flist" == "$DIALOG_CANCEL" ]]
                then
                    kate $CHOICE > /dev/null 2>&1
                fi
                ;;
            d)
                git diff
                read -p "Press [ENTER] to continue." op
                ;;
            s)
                git status
                read -p "Press [ENTER] to continue." op
                ;;
            q)
                exit 0
                ;;
    esac
done
