#!/bin/bash

# Slackware build scipt for 0scripts

# Copyright 2023-2025 Antonio Leal, Porto Salvo, Oeiras, Portugal
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e
clear
PKGNAME=${PWD##*/}
echo "Building Package $PKGNAME:"
echo

echo "--------------------------------------------------------------------------------"
echo
read -p "Run sbolint? (Y/n) " op
if [ "$op" = "y" ] || [ "$op" = "Y" ] || [ "$op" = "" ]; then
    if ! [ -f 0/slackbuild/$PKGNAME.tar.gz ]; then
        mkdir -p 0/slackbuild
        echo "Dummy temporary file to trick sbolint." > 0/slackbuild/$PKGNAME.tar.gz
    fi
    sbolint .
fi

echo "--------------------------------------------------------------------------------"
echo
read -p "Run SlackBuild for Package $PKGNAME? (Y/n) " op
if [ "$op" = "y" ] || [ "$op" = "Y" ] || [ "$op" = "" ]; then
    read -p "Define MAKEFLAGS=-j<value> or press enter for <value>=10 > " mf
    if [ "$mf" = "" ]; then
        mf=10
        echo "Using MAKEFLAGS=-j10"
    else
        echo "Using MAKEFLAGS=-j${mf}"
    fi
    sudo MAKEFLAGS=-j${mf} sh ./$PKGNAME.SlackBuild
fi

echo "--------------------------------------------------------------------------------"
echo
VERSION=`cat *.info | grep VERSION | cut -d"\"" -f2`
echo "Tarballs available at /tmp:"
ls /tmp/$PKGNAME-$VERSION* -lasth
TARBALL=`ls /tmp/$PKGNAME-$VERSION* -1t | head -n1`


echo "--------------------------------------------------------------------------------"
echo
read -p "Run sbopkglint $TARBALL ? (Y/n) " op
if [ "$op" = "y" ] || [ "$op" = "Y" ] || [ "$op" = "" ]; then
    sbopkglint $TARBALL
fi

echo "--------------------------------------------------------------------------------"
echo
read -p "Install $TARBALL ? (Y/n) " op
if [ "$op" = "y" ] || [ "$op" = "Y" ] || [ "$op" = "" ]; then
    sudo /sbin/upgradepkg --install-new --reinstall $TARBALL
fi


echo "--------------------------------------------------------------------------------"
echo
read -p "Create SlackBuild package by running 0tar? (Y/n) " op
if [ "$op" = "y" ] || [ "$op" = "Y" ] || [ "$op" = "" ]; then
    0tar
fi
