#!/bin/bash

# Slackware 0script to discover package dependencies

# Copyright 2023-2025 Antonio Leal, Porto Salvo, Oeiras, Portugal
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# This script searches the slackare dependencies of an executable
# it uses the script 'whichpkg' available at
# http://www.linuxquestions.org/questions/showthread.php?postid=899459#post899459

msg="Slackware package dependencies of executable $1"
base="slackware_package_dependencies"
fich="$base.txt"
aux="$base.aux"
rm -rf $fich

clear
echo $msg

#get all the ELF dependencies
for lib in `readelf -d $1 | grep "NEEDED" | awk '{ print substr($5,2,length($5)-2) }'`
do
	echo $lib >> $fich
done
#remove repetitions
awk '!seen[$0]++' $fich > $aux

echo "*******************************************************************************************************************"
echo "these are library dependencies:"
cat $aux
echo

echo "*******************************************************************************************************************"
echo "now finding their packages:"
echo "$msg" > $fich
#print the version on the screen
IFS=$'\n' # set the Internal Field Separator to newline
for lib in $(cat "$aux")
do
        pkg="`0whichpkg $lib`"
        echo "$pkg"
        echo "$pkg" >> $fich
done

rm $aux
echo "*******************************************************************************************************************"
echo "Done."
