#!/bin/bash

# Slackware 0script to takeover a package

# Copyright 2026 Antonio Leal, Porto Salvo, Oeiras, Portugal
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

YOURNAME="Antonio Leal"
YOUREMAIL="antonioleal@yahoo.com"
YOURCOPYRIGHT="# Copyright 2026 Antonio Leal, Porto Salvo, Oeiras, Portugal"

set -e
clear
if [ "$1" = "" ]; then
    read -p "Which package do you want to take over? > " PKGNAME
else
    PKGNAME=$1
fi
echo "Taking over $PKGNAME"

cd $HOME/slackware-builds/slackbuilds
INFO=$( find $HOME/slackware-builds/slackbuilds -name "${PKGNAME}.info" -print )
if [ "$INFO" == "" ]; then
    echo "$PKGNAME not found. Aborting"
    exit 1
fi

DIR=$(dirname $INFO)
cd $DIR
cd ..
CATEGORY=${PWD##*/}
cd $HOME/slackware-builds/myslackbuilds/
mkdir -p $CATEGORY
cd $CATEGORY
cp -avxu $DIR $HOME/slackware-builds/myslackbuilds/$CATEGORY
cd $PKGNAME
sed -i -e "s/MAINTAINER=.*/MAINTAINER=\"${YOURNAME}\"/" $PKGNAME.info
sed -i -e "s/EMAIL=.*/EMAIL=\"${YOUREMAIL}\"/" $PKGNAME.info

LINE=$(grep -n -i "Copyright" $PKGNAME.SlackBuild | head -1 | cut -d":" -f1)
sed -i "${LINE}i $YOURCOPYRIGHT" $PKGNAME.SlackBuild
echo "Done."
