#!/bin/bash

# Slackware updater script for notepad++

# Copyright 2025-2025 Antonio Leal, Porto Salvo, Oeiras, Portugal
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=notepad++
set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR

################################
# check versions               #
################################
#NEWVERSION=`curl -s https://notepad-plus-plus.org/index.xml | grep Download | head -n1 | awk '{print substr($3,2,length($3)-1)}'`
# TAG=`curl -s https://api.github.com/repos/notepad-plus-plus/notepad-plus-plus/releases/latest | jq -r '.tag_name'`
TAG=$(gh release view -R notepad-plus-plus/notepad-plus-plus --json tagName --jq '.tagName')
NEWVERSION=${TAG:1}
TARBALL1=npp.${NEWVERSION}.Installer.exe
TARBALL2=npp.${NEWVERSION}.Installer.x64.exe
URL1="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/${TAG}/npp.${NEWVERSION}.Installer.exe"
URL2="https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/${TAG}/npp.${NEWVERSION}.Installer.x64.exe"

VERSION=`cat version`
if [ "$VERSION" = "$NEWVERSION" ]
then
    echo "is at version $VERSION"
    export RET0=""
else
    ################################
    # check for testonly parameter #
    ################################
    if [ "$ARG0" = "TESTONLY" ]
    then
        echo "has a new version $NEWVERSION"
        export RET0=$NEWVERSION
        return
    fi
    ################################
    # download tarball             #
    ################################
    wget $URL1
    if [ ! -f ./$TARBALL1 ]
    then
        echo "File $TARBALL1 not found, aborting..."
        exit
    fi
    wget $URL2
    if [ ! -f ./$TARBALL2 ]
    then
        echo "File $TARBALL2 not found, aborting..."
        exit
    fi
    # delete old tarball and place new one
    rm -rf ../*.exe 2> /dev/null
    mv *.exe ..

    ################################
    # write templates              #
    ################################
    MD51=`md5sum ../$TARBALL1 | cut -d " " -f 1`
    MD52=`md5sum ../$TARBALL2 | cut -d " " -f 1`
    #DATEVERSION=`tar tvfz ../$TARBALL | head -n1 | awk '{ print $4 }' | awk 'BEGIN { FS = "-" } ; { print $1$2$3 }'`

    sed -e "s/_version_/${NEWVERSION}/g" -e "s/_md51_/$MD51/g" -e "s/_md52_/$MD52/g" $SCRIPT_DIR/template/${PRGNAM}.info.template > ../${PRGNAM}.info
    sed -e "s/_version_/${NEWVERSION}/g" $SCRIPT_DIR/template/${PRGNAM}.SlackBuild.template > ../${PRGNAM}.SlackBuild
    sed -e "s/_version_/${NEWVERSION}/g" $SCRIPT_DIR/template/${PRGNAM}.template > ../${PRGNAM}

    chmod 644 ../${PRGNAM}.SlackBuild
    echo "$NEWVERSION" > version
    echo "has a new version $NEWVERSION"
    export RET0=$NEWVERSION
fi
